### ISSUE TITLE
Add support for vertical split like UI

### ISSUE THREAD

**Issue by Ferriccc** [A7Lavinraj/assistant.nvim#36]
When test data is long or output is long, having a option to change from floating UI to nvim's vsplit kind of UI would be very helpful.

Floating UI is great but, it wastes a lot of space at top and bottom, vsplit kind of UI will use screen real estate more efficiently.

**Comment by A7Lavinraj** [comment]
Thanks for the feedback, I have started working on this fix, and changes will be reflected in the next update.
