### ISSUE TITLE
Bug Report: Test Cases Are Not Persistent When Toggling the Plugin

### ISSUE THREAD

**Issue by Giovanni0114** [A7Lavinraj/assistant.nvim#48]
## Describe the Bug

Test cases are not retained when toggling the plugin. If the assistant view is closed, all previously added test cases are lost upon reopening.

## Steps to Reproduce

- Install the plugin using default options.
- Open the Assistant view using :AssistantToggle.
- Add test cases in the view.
- Close the Assistant view using :AssistantToggle.
- Reopen the Assistant view using :AssistantToggle.

## Expected Behavior
- Previously added test cases should persist and remain available when reopening the Assistant view.

## Actual Behavior
- All test cases are deleted when the view is closed and reopened.

## Environment

OS: Linux 6.12.1-arch1-1
Neovim Version: NVIM v0.10.2
assistant.nvim Version: Commit 68f8697

**Comment by A7Lavinraj** [comment]
Alright i will patch this bug as soon as possible, keep patience

**Comment by A7Lavinraj** [comment]
That request was resolved now. Thanks for keeping patience!

`commit e66b07f537e1f1c487f24cd1e39785097e96b2dd`
