### ISSUE TITLE
 Bug Report: Incorrect Behavior of `$FILENAME_WITHOUT_EXTENSION` and `$FILENAME_WITH_EXTENSION` Variables

### ISSUE THREAD

**Issue by Giovanni0114** [A7Lavinraj/assistant.nvim#49]
**Describe the Bug**  
The variables `$FILENAME_WITHOUT_EXTENSION` and `$FILENAME_WITH_EXTENSION` are not functioning as expected:  
- `$FILENAME_WITHOUT_EXTENSION` incorrectly includes the file extension (e.g., `main.cpp`, `main.py`).  
- `$FILENAME_WITH_EXTENSION` duplicates the file extension (e.g., `main.cpp.cpp`, `main.py.py`).  

**Steps to Reproduce**  
1. Use the plugin with the default configuration.  
2. Attempt to run any test that utilizes the variables `$FILENAME_WITHOUT_EXTENSION` or `$FILENAME_WITH_EXTENSION`.  

**Expected Behavior**  
- `$FILENAME_WITHOUT_EXTENSION` should contain the filename **without** the extension (e.g., `main`).  
- `$FILENAME_WITH_EXTENSION` should contain the filename **with** the correct extension (e.g., `main.cpp`, `main.py`).  

**Actual Behavior**  
- `$FILENAME_WITHOUT_EXTENSION` includes the extension (e.g., `main.cpp`, `main.py`).  
- `$FILENAME_WITH_EXTENSION` appends the extension twice (e.g., `main.cpp.cpp`, `main.py.py`).  

**Environment**  
- **OS:** Linux 6.12.1-arch1-1  
- **Neovim Version:** NVIM v0.10.2  
- **assistant.nvim Version:** Commit 68f8697  

**Additional Notes**  
- This behavior is consistent across different test files and programming languages.  
- The issue may be related to how the filename parsing logic is implemented.

**Comment by A7Lavinraj** [comment]
Can you send me your config for commands

**Comment by Giovanni0114** [comment]
> Can you send me your config for commands

Working config:

```lua
return { "A7lavinraj/assistant.nvim",
    keys = {
        { "<leader>a", "<cmd>AssistantToggle<cr>", desc = "Toggle Assistant.nvim window" }
    },
    opts = {
        commands = {
            python = {
                extension = "py",
                compile = nil,
                execute = {
                    main = "python3",
                    args = { "$FILENAME_WITHOUT_EXTENSION" },
                },
            },
            cpp = {
                extension = "cpp",
                compile = {
                    main = "g++",
                    args = { "$FILENAME_WITHOUT_EXTENSION", "-o", "test" },
                },
                execute = {
                    main = "./test",
                    args = nil,
                },
            },
        },
        ui = {
            icons = {
                success = "",
                failure = "",
                unknown = "",
                loading = { "󰸴", "󰸵", "󰸸", "󰸷", "󰸶" },
            },
        },
        core = {
            process_budget = 5000,
        },
    }
}
```

Not working config (drom default):
```lua
...
 commands = {
    python = {
      extension = "py",
      compile = nil,
      execute = {
        main = "python3",
        args = { "$FILENAME_WITH_EXTENSION" },
      },
    },
    cpp = {
      extension = "cpp",
      compile = {
        main = "g++",
        args = { "$FILENAME_WITH_EXTENSION", "-o", "$FILENAME_WITHOUT_EXTENSION" },
      },
      execute = {
        main = "./$FILENAME_WITHOUT_EXTENSION",
        args = nil,
      },
    },
  },
  ...
  ```

**Comment by A7Lavinraj** [comment]
> > Can you send me your config for commands
> 
> Working config:
> 
> ```lua
> return { "A7lavinraj/assistant.nvim",
>     keys = {
>         { "<leader>a", "<cmd>AssistantToggle<cr>", desc = "Toggle Assistant.nvim window" }
>     },
>     opts = {
>         commands = {
>             python = {
>                 extension = "py",
>                 compile = nil,
>                 execute = {
>                     main = "python3",
>                     args = { "$FILENAME_WITHOUT_EXTENSION" },
>                 },
>             },
>             cpp = {
>                 extension = "cpp",
>                 compile = {
>                     main = "g++",
>                     args = { "$FILENAME_WITHOUT_EXTENSION", "-o", "test" },
>                 },
>                 execute = {
>                     main = "./test",
>                     args = nil,
>                 },
>             },
>         },
>         ui = {
>             icons = {
>                 success = "",
>                 failure = "",
>                 unknown = "",
>                 loading = { "󰸴", "󰸵", "󰸸", "󰸷", "󰸶" },
>             },
>         },
>         core = {
>             process_budget = 5000,
>         },
>     }
> }
> ```
> 
> Not working config (from default):
> 
> ```lua
> ...
>  commands = {
>     python = {
>       extension = "py",
>       compile = nil,
>       execute = {
>         main = "python3",
>         args = { "$FILENAME_WITH_EXTENSION" },
>       },
>     },
>     cpp = {
>       extension = "cpp",
>       compile = {
>         main = "g++",
>         args = { "$FILENAME_WITH_EXTENSION", "-o", "$FILENAME_WITHOUT_EXTENSION" },
>       },
>       execute = {
>         main = "./$FILENAME_WITHOUT_EXTENSION",
>         args = nil,
>       },
>     },
>   },
>   ...
> ```

I tried both config and both are working perfectly for me

**Comment by A7Lavinraj** [comment]
this is the config i am using according to your report, please verify it

```lua
return {
  "assistant.nvim",
  lazy = false,
  enabled = true,
  dependencies = { "stevearc/dressing.nvim" },
  dir = "~/workspace/development/assistant.nvim",
  keys = {
    { "<leader>a", "<cmd>AssistantToggle<cr>", desc = "Toggle Assistant.nvim window" },
  },
  opts = {
    commands = {
      python = {
        extension = "py",
        compile = nil,
        execute = {
          main = "python3",
          args = { "$FILENAME_WITH_EXTENSION" },
        },
      },
      cpp = {
        extension = "cpp",
        compile = {
          main = "g++",
          args = { "$FILENAME_WITH_EXTENSION", "-o", "test" },
        },
        execute = {
          main = "./test",
          args = nil,
        },
      },
    },
  },
}
```

**Comment by Giovanni0114** [comment]
Yes, on my machine this config would result in issues that I described in report

**Comment by A7Lavinraj** [comment]
what error you facing actually?

**Comment by Giovanni0114** [comment]
![image](https://github.com/user-attachments/assets/73b8be09-fee6-4d50-a834-49739e63f16d)

**Comment by A7Lavinraj** [comment]
Well i need some time to test and find the issue. stay tuned!

**Comment by Giovanni0114** [comment]
i do believe that the issue is with the initial setting the filename in `ui/init.lua` there should be 
```
    name = vim.fn.expand("%:t:r")
```
instead of 

```
    name = vim.fn.expand("%:t")
```

**Comment by Giovanni0114** [comment]
after this fix it works for me

**Comment by A7Lavinraj** [comment]
Oh now i got it, i have to separate them(filename and extension) when working with custom source files, thanks for helping me out!

**Comment by A7Lavinraj** [comment]
Do you want to make pull request for this fix? Otherwise i will do it anyways🙂

**Comment by Giovanni0114** [comment]
this is such simple fix, there is no need for PR :D

**Comment by A7Lavinraj** [comment]
Now it is fixed and pushed
